# Dependencies
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: Adrian Arroyo's Blog
tagline: If everybody is thinking alike, then somebody isn't thinking - George S. Patton
url: http://adrianarroyocalle.github.io
paginate: 1
baseurl: /blog/
author:
  name: Adri√°n Arroyo Calle
  url: https://adrianarroyocalle.github.io
  email: adrian.arroyocalle@gmail.com
timezone: Europe/Madrid
encoding: utf-8
# Custom vars
version: 1.0.0
github:
  repo: https://github.com/AdrianArroyoCalle/blog
pages_list:
  About: "/about"
  Archive: "/archive"
  Feed: "/atom.xml"
