# Dependencies
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments

# Permalinks
permalink: pretty

# Setup
title: El blog de Adrián Arroyo
tagline: Si todo el mundo piensa lo mismo, entonces alguien no está pensando - George S. Patton
description: Este es mi blog personal, espero que lo disfrutes visitando.
url: http://adrianarroyocalle.github.io
paginate: 5
baseurl: /blog/
fullurl: /blog
author:
  name: Adrián Arroyo Calle
  url: https://adrianarroyocalle.github.io
  email: adrian.arroyocalle@gmail.com
timezone: Europe/Madrid
encoding: utf-8
future: false
# Custom vars
version: 1.0.0
github:
  repo: https://github.com/AdrianArroyoCalle/blog
pages_list:
  Acerca: "about"
  Archivo: "archive"
  Feed: "atom.xml"
